- name: 1Password (Arch)
  when: ansible_facts['os_family'] == "Archlinux"
  ansible.builtin.include_tasks:
    file: aur-helper.yml
  vars:
    package_name: 1password
    package_provides: 1password

- name: 1Password (Debian)
  when: ansible_facts["os_family"] == "Debian"
  block:
    - name: Add APT key for 1Password (Debian)
      ansible.builtin.shell:
        cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        creates: /usr/share/keyrings/1password-archive-keyring.gpg

    - name: Add APT repository for 1Password (Debian)
      ansible.builtin.apt_repository:
        filename: 1password.list
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
        state: present
        update_cache: yes
    
    - name: Add debsig-verify policy for 1Password (Debian)
      ansible.builtin.shell:
        cmd: |
          mkdir -p /etc/debsig/policies/AC2D62742012EA22/
          curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
          mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
          curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
    
    - name: Install 1Password (Debian)
      ansible.builtin.apt:
        name: 1password

- name: 1Password (RedHat)
  when: ansible_facts["os_family"] == "RedHat"
  block:
    - name: Add yum repository for 1Password (RedHat)
      ansible.builtin.yum_repository:
        baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
        description: 1Password Stable Channel
        gpgcheck: true
        gpgkey: https://downloads.1password.com/linux/keys/1password.asc
        name: 1password
        repo_gpgcheck: true
      register: yum_repo

    - name: Install 1Password (RedHat)
      ansible.builtin.dnf:
        name: 1password
        state: present
